still red
=== RUN   TestProvider
    provider_test.go:15: Step 1/1 error: Error running pre-apply plan: exit status 1

        Error: Invalid data source

          on terraform_plugin_test.tf line 12, in data "github_repository" "example":
          12: 				data "github_repository" "example" {

        The provider hashicorp/github does not support data source
        "github_repository".
--- FAIL: TestProvider (0.13s)